// Generated by lsc from answer-check-rule.ts

function runsAnswerCheck(decided: bool, checkable: bool): bool
{
  (!(decided) || checkable)
}

lemma runsAnswerCheck_ensures(decided: bool, checkable: bool)
  ensures (runsAnswerCheck(decided, checkable) <==> !((decided && !(checkable))))
{
}
