// Generated by lsc from answer-check-rule.ts

datatype TriageOutcome = checked | skipped | undecided

function runsAnswerCheck(decided: bool, checkable: bool): bool
{
  (!(decided) || checkable)
}

lemma runsAnswerCheck_ensures(decided: bool, checkable: bool)
  ensures (runsAnswerCheck(decided, checkable) <==> !((decided && !(checkable))))
{
}

function triageOutcome(decided: bool, checkable: bool): TriageOutcome
{
  if !(decided) then
    TriageOutcome.undecided
  else
    if checkable then
      TriageOutcome.checked
    else
      TriageOutcome.skipped
}

lemma triageOutcome_ensures(decided: bool, checkable: bool)
  ensures (triageOutcome(decided, checkable).skipped? <==> !(runsAnswerCheck(decided, checkable)))
  ensures (!(decided) ==> triageOutcome(decided, checkable).undecided?)
  ensures (decided ==> checkable ==> triageOutcome(decided, checkable).checked?)
{
}

function turnCheckable(requestsCheckable: bool, replyCheckable: bool): bool
{
  (requestsCheckable || replyCheckable)
}

lemma turnCheckable_ensures(requestsCheckable: bool, replyCheckable: bool)
  ensures (turnCheckable(requestsCheckable, replyCheckable) <==> (requestsCheckable || replyCheckable))
{
}
