// Generated by lsc from application-rule.ts

datatype ApplicationAdmission = apply | recover | stale_review | refresh

datatype PathContent = before | after | other

datatype CommitStep = install | done | stop

datatype RestoreStep = done | stop | restore

datatype ApplicationOutcome = applied | not_applied | recovery_required

function applicationAdmission(unfinished: bool, reviewCurrent: bool, sourceUnchanged: bool): ApplicationAdmission
{
  if unfinished then
    ApplicationAdmission.recover
  else
    if !(reviewCurrent) then
      ApplicationAdmission.stale_review
    else
      if sourceUnchanged then
        ApplicationAdmission.apply
      else
        ApplicationAdmission.refresh
}

lemma applicationAdmission_ensures(unfinished: bool, reviewCurrent: bool, sourceUnchanged: bool)
  ensures (applicationAdmission(unfinished, reviewCurrent, sourceUnchanged).apply? <==> ((!(unfinished) && reviewCurrent) && sourceUnchanged))
  ensures (unfinished ==> applicationAdmission(unfinished, reviewCurrent, sourceUnchanged).recover?)
  ensures (!(unfinished) ==> !(reviewCurrent) ==> applicationAdmission(unfinished, reviewCurrent, sourceUnchanged).stale_review?)
  ensures (!(unfinished) ==> reviewCurrent ==> !(sourceUnchanged) ==> applicationAdmission(unfinished, reviewCurrent, sourceUnchanged).refresh?)
{
}

function commitStep(content: PathContent): CommitStep
{
  if content.before? then
    CommitStep.install
  else
    if content.after? then
      CommitStep.done
    else
      CommitStep.stop
}

lemma commitStep_ensures(content: PathContent)
  ensures (commitStep(content).install? <==> content.before?)
  ensures (commitStep(content).done? <==> content.after?)
  ensures (commitStep(content).stop? <==> content.other?)
{
}

function restoreStep(touched: bool, content: PathContent): RestoreStep
{
  if !(touched) then
    RestoreStep.done
  else
    if content.after? then
      RestoreStep.restore
    else
      if content.before? then
        RestoreStep.done
      else
        RestoreStep.stop
}

lemma restoreStep_ensures(touched: bool, content: PathContent)
  ensures (restoreStep(touched, content).restore? <==> (touched && content.after?))
  ensures (restoreStep(touched, content).done? <==> (!(touched) || content.before?))
  ensures (restoreStep(touched, content).stop? <==> (touched && content.other?))
{
}

function applicationOutcome(paths: int, after: int, unaffected: int): ApplicationOutcome
  requires (paths > 0)
  requires (after >= 0)
  requires (unaffected >= 0)
  requires (after <= paths)
  requires (unaffected <= paths)
{
  if (after == paths) then
    ApplicationOutcome.applied
  else
    if (unaffected == paths) then
      ApplicationOutcome.not_applied
    else
      ApplicationOutcome.recovery_required
}

lemma applicationOutcome_ensures(paths: int, after: int, unaffected: int)
  requires (paths > 0)
  requires (after >= 0)
  requires (unaffected >= 0)
  requires (after <= paths)
  requires (unaffected <= paths)
  ensures (applicationOutcome(paths, after, unaffected).applied? <==> (after == paths))
  ensures (applicationOutcome(paths, after, unaffected).not_applied? <==> ((after < paths) && (unaffected == paths)))
  ensures (applicationOutcome(paths, after, unaffected).recovery_required? <==> ((after < paths) && (unaffected < paths)))
{
}
