// Generated by lsc from application-rule.ts

datatype ApplicationAdmission = apply | recover | stale_review | refresh

datatype PathContent = before | after | other

datatype CommitStep = install | done | stop

datatype RestoreStep = done | stop | restore

datatype ApplicationOutcome = applied | not_applied | recovery_required

datatype WriteEvidence = written | not_written | unknown

datatype JournalStep = done | none | intended | untouched

function applicationAdmission(unfinished: bool, reviewCurrent: bool, sourceUnchanged: bool): ApplicationAdmission
{
  if unfinished then
    ApplicationAdmission.recover
  else
    if !(reviewCurrent) then
      ApplicationAdmission.stale_review
    else
      if sourceUnchanged then
        ApplicationAdmission.apply
      else
        ApplicationAdmission.refresh
}

lemma applicationAdmission_ensures(unfinished: bool, reviewCurrent: bool, sourceUnchanged: bool)
  ensures (applicationAdmission(unfinished, reviewCurrent, sourceUnchanged).apply? <==> ((!(unfinished) && reviewCurrent) && sourceUnchanged))
  ensures (unfinished ==> applicationAdmission(unfinished, reviewCurrent, sourceUnchanged).recover?)
  ensures (!(unfinished) ==> !(reviewCurrent) ==> applicationAdmission(unfinished, reviewCurrent, sourceUnchanged).stale_review?)
  ensures (!(unfinished) ==> reviewCurrent ==> !(sourceUnchanged) ==> applicationAdmission(unfinished, reviewCurrent, sourceUnchanged).refresh?)
{
}

function commitStep(content: PathContent): CommitStep
{
  if content.before? then
    CommitStep.install
  else
    if content.after? then
      CommitStep.done
    else
      CommitStep.stop
}

lemma commitStep_ensures(content: PathContent)
  ensures (commitStep(content).install? <==> content.before?)
  ensures (commitStep(content).done? <==> content.after?)
  ensures (commitStep(content).stop? <==> content.other?)
{
}

function writeEvidence(step: JournalStep, installed: bool, removal: bool): WriteEvidence
{
  if step.done? then
    WriteEvidence.written
  else
    if (step.none? || step.untouched?) then
      WriteEvidence.not_written
    else
      if (installed || removal) then
        WriteEvidence.written
      else
        WriteEvidence.unknown
}

lemma writeEvidence_ensures(step: JournalStep, installed: bool, removal: bool)
  ensures (writeEvidence(step, installed, removal).written? <==> (step.done? || (step.intended? && (installed || removal))))
  ensures (writeEvidence(step, installed, removal).not_written? <==> (step.none? || step.untouched?))
  ensures (writeEvidence(step, installed, removal).unknown? <==> ((step.intended? && !(installed)) && !(removal)))
{
}

function restoreStep(evidence: WriteEvidence, content: PathContent): RestoreStep
{
  if (evidence.not_written? || content.before?) then
    RestoreStep.done
  else
    if (evidence.written? && content.after?) then
      RestoreStep.restore
    else
      RestoreStep.stop
}

lemma restoreStep_ensures(evidence: WriteEvidence, content: PathContent)
  ensures (restoreStep(evidence, content).restore? <==> (evidence.written? && content.after?))
  ensures (restoreStep(evidence, content).done? <==> (evidence.not_written? || content.before?))
  ensures (restoreStep(evidence, content).stop? <==> (((!evidence.not_written?) && (!content.before?)) && !((evidence.written? && content.after?))))
{
}

function applicationOutcome(paths: int, after: int, unaffected: int): ApplicationOutcome
  requires (paths > 0)
  requires (after >= 0)
  requires (unaffected >= 0)
  requires (after <= paths)
  requires (unaffected <= paths)
{
  if (after == paths) then
    ApplicationOutcome.applied
  else
    if (unaffected == paths) then
      ApplicationOutcome.not_applied
    else
      ApplicationOutcome.recovery_required
}

lemma applicationOutcome_ensures(paths: int, after: int, unaffected: int)
  requires (paths > 0)
  requires (after >= 0)
  requires (unaffected >= 0)
  requires (after <= paths)
  requires (unaffected <= paths)
  ensures (applicationOutcome(paths, after, unaffected).applied? <==> (after == paths))
  ensures (applicationOutcome(paths, after, unaffected).not_applied? <==> ((after < paths) && (unaffected == paths)))
  ensures (applicationOutcome(paths, after, unaffected).recovery_required? <==> ((after < paths) && (unaffected < paths)))
{
}
