// Generated by lsc from check-origin-rule.ts

datatype CheckOutcome = passed | failed | timed_out | cancelled | not_started | unconfirmed | changed_files

datatype CheckOrigin = introduced | preexisting | unknown

datatype TestStatus = passed | failed | skipped | absent | unread

datatype ReportedTest = passed | failed | skipped | none

function baseTestStatus(reported: ReportedTest, covered: bool): TestStatus
{
  if reported.passed? then
    TestStatus.passed
  else
    if reported.failed? then
      TestStatus.failed
    else
      if reported.skipped? then
        TestStatus.skipped
      else
        if covered then
          TestStatus.absent
        else
          TestStatus.unread
}

lemma baseTestStatus_ensures(reported: ReportedTest, covered: bool)
  ensures (reported.passed? ==> baseTestStatus(reported, covered).passed?)
  ensures (reported.failed? ==> baseTestStatus(reported, covered).failed?)
  ensures (reported.skipped? ==> baseTestStatus(reported, covered).skipped?)
  ensures (reported.none? ==> covered ==> baseTestStatus(reported, covered).absent?)
  ensures (reported.none? ==> !(covered) ==> baseTestStatus(reported, covered).unread?)
  ensures (baseTestStatus(reported, covered).absent? ==> (reported.none? && covered))
{
}

function testOrigin(candidate: TestStatus, base: TestStatus): CheckOrigin
{
  if (!candidate.failed?) then
    CheckOrigin.unknown
  else
    if (base.passed? || base.absent?) then
      CheckOrigin.introduced
    else
      if base.failed? then
        CheckOrigin.preexisting
      else
        CheckOrigin.unknown
}

lemma testOrigin_ensures(candidate: TestStatus, base: TestStatus)
  ensures ((!candidate.failed?) ==> testOrigin(candidate, base).unknown?)
  ensures (candidate.failed? ==> (base.passed? || base.absent?) ==> testOrigin(candidate, base).introduced?)
  ensures (testOrigin(candidate, base).introduced? ==> (candidate.failed? && (base.passed? || base.absent?)))
  ensures (candidate.failed? ==> base.failed? ==> testOrigin(candidate, base).preexisting?)
  ensures (testOrigin(candidate, base).preexisting? ==> (candidate.failed? && base.failed?))
{
}

function checkOrigin(candidate: CheckOutcome, base: CheckOutcome, introducedTests: int): CheckOrigin
  requires (introducedTests >= 0)
{
  if ((!candidate.failed?) && (!candidate.timed_out?)) then
    CheckOrigin.unknown
  else
    if base.passed? then
      CheckOrigin.introduced
    else
      if ((introducedTests > 0) && (base.failed? || base.timed_out?)) then
        CheckOrigin.introduced
      else
        if (base == candidate) then
          CheckOrigin.preexisting
        else
          CheckOrigin.unknown
}

lemma checkOrigin_ensures(candidate: CheckOutcome, base: CheckOutcome, introducedTests: int)
  requires (introducedTests >= 0)
  ensures (!((candidate.failed? || candidate.timed_out?)) ==> checkOrigin(candidate, base, introducedTests).unknown?)
  ensures ((candidate.failed? || candidate.timed_out?) ==> base.passed? ==> checkOrigin(candidate, base, introducedTests).introduced?)
  ensures ((candidate.failed? || candidate.timed_out?) ==> (introducedTests > 0) ==> (base.failed? || base.timed_out?) ==> checkOrigin(candidate, base, introducedTests).introduced?)
  ensures ((candidate.failed? || candidate.timed_out?) ==> (introducedTests == 0) ==> (base == candidate) ==> checkOrigin(candidate, base, introducedTests).preexisting?)
  ensures (checkOrigin(candidate, base, introducedTests).introduced? ==> (base.passed? || ((introducedTests > 0) && (base.failed? || base.timed_out?))))
  ensures (checkOrigin(candidate, base, introducedTests).preexisting? ==> (((base == candidate) && (!candidate.passed?)) && (introducedTests == 0)))
{
}
