// Generated by lsc from check-scope-rule.ts

function runsRelatedForm(hasRelatedForm: bool, changedFiles: bool, deletesFiles: bool, changesWhatChecks: bool, lastRound: bool): bool
{
  if (!(hasRelatedForm) || !(changedFiles)) then
    false
  else
    if (deletesFiles || changesWhatChecks) then
      false
    else
      !(lastRound)
}

lemma runsRelatedForm_ensures(hasRelatedForm: bool, changedFiles: bool, deletesFiles: bool, changesWhatChecks: bool, lastRound: bool)
  ensures (runsRelatedForm(hasRelatedForm, changedFiles, deletesFiles, changesWhatChecks, lastRound) <==> ((((hasRelatedForm && changedFiles) && !(deletesFiles)) && !(changesWhatChecks)) && !(lastRound)))
{
}

function owesWholeCommand(ranRelatedForm: bool): bool
{
  ranRelatedForm
}

lemma owesWholeCommand_ensures(ranRelatedForm: bool)
  ensures (owesWholeCommand(ranRelatedForm) <==> ranRelatedForm)
{
}
