// Generated by lsc from check-origin-rule.ts

datatype CheckOutcome = passed | failed | timed_out | cancelled | not_started | unconfirmed | changed_files

datatype CheckOrigin = introduced | preexisting | unknown

function checkOrigin(candidate: CheckOutcome, base: CheckOutcome): CheckOrigin
{
  if ((!candidate.failed?) && (!candidate.timed_out?)) then
    CheckOrigin.unknown
  else
    if base.passed? then
      CheckOrigin.introduced
    else
      if (base == candidate) then
        CheckOrigin.preexisting
      else
        CheckOrigin.unknown
}

lemma checkOrigin_ensures(candidate: CheckOutcome, base: CheckOutcome)
  ensures (!((candidate.failed? || candidate.timed_out?)) ==> checkOrigin(candidate, base).unknown?)
  ensures ((candidate.failed? || candidate.timed_out?) ==> base.passed? ==> checkOrigin(candidate, base).introduced?)
  ensures ((candidate.failed? || candidate.timed_out?) ==> (base == candidate) ==> checkOrigin(candidate, base).preexisting?)
  ensures (checkOrigin(candidate, base).introduced? ==> base.passed?)
  ensures (checkOrigin(candidate, base).preexisting? ==> ((base == candidate) && (!candidate.passed?)))
{
}
