// Generated by lsc from codex-plan-rule.ts

function planServes(onFreePlan: bool, refusedOnFree: bool): bool
{
  !((onFreePlan && refusedOnFree))
}

lemma planServes_ensures(onFreePlan: bool, refusedOnFree: bool)
  ensures (planServes(onFreePlan, refusedOnFree) <==> !((onFreePlan && refusedOnFree)))
{
}
