// Generated by lsc from command-rule.ts

method beginsWith(words: seq<string>, rule: seq<string>) returns (res: bool)
  ensures (res == (((|rule| > 0) && (|rule| <= |words|)) && forall i: nat :: ((i < |rule|) ==> (rule[i] == words[i]))))
{
  if ((|rule| == 0) || (|rule| > |words|)) {
    return false;
  }
  var i := 0;
  while (i < |rule|)
    invariant (0 <= i)
    invariant (i <= |rule|)
    invariant forall j: nat :: ((j < i) ==> (rule[j] == words[j]))
  {
    if (rule[i] != words[i]) {
      return false;
    }
    i := (i + 1);
  }
  return true;
}

method savableRule(rule: seq<string>, forbidden: seq<string>) returns (res: bool)
  ensures (res == ((|rule| >= 2) && forall i: nat :: ((i < |forbidden|) ==> (forbidden[i] != rule[0]))))
{
  if (|rule| < 2) {
    return false;
  }
  var i := 0;
  while (i < |forbidden|)
    invariant (0 <= i)
    invariant (i <= |forbidden|)
    invariant forall j: nat :: ((j < i) ==> (forbidden[j] != rule[0]))
  {
    if (forbidden[i] == rule[0]) {
      return false;
    }
    i := (i + 1);
  }
  return true;
}

method coveredPart(words: seq<string>, rules: seq<seq<string>>) returns (res: bool)
  ensures (res == exists r: nat :: ((((r < |rules|) && (|rules[r]| > 0)) && (|rules[r]| <= |words|)) && forall i: nat :: ((i < |rules[r]|) ==> (rules[r][i] == words[i]))))
{
  var i_rule_idx := 0;
  while i_rule_idx < |rules|
    invariant (i_rule_idx <= |rules|)
    invariant forall k: nat :: ((k < i_rule_idx) ==> !((((|rules[k]| > 0) && (|rules[k]| <= |words|)) && forall i: nat :: ((i < |rules[k]|) ==> (rules[k][i] == words[i])))))
  {
    var rule := rules[i_rule_idx];
    var i_t0 := beginsWith(words, rule);
    if i_t0 {
      return true;
    }
    i_rule_idx := i_rule_idx + 1;
  }
  return false;
}

method runsWithoutAsking(plain: bool, parts: seq<seq<string>>, rules: seq<seq<string>>) returns (res: bool)
  ensures (res == ((plain && (|parts| > 0)) && forall q: nat :: ((q < |parts|) ==> ((|parts[q]| >= 0) && exists r: nat :: ((((r < |rules|) && (|rules[r]| > 0)) && (|rules[r]| <= |parts[q]|)) && forall i: nat :: ((i < |rules[r]|) ==> (rules[r][i] == parts[q][i])))))))
{
  if (!(plain) || (|parts| == 0)) {
    return false;
  }
  var i_part_idx := 0;
  while i_part_idx < |parts|
    invariant (i_part_idx <= |parts|)
    invariant forall k: nat :: ((k < i_part_idx) ==> ((|parts[k]| >= 0) && exists r: nat :: ((((r < |rules|) && (|rules[r]| > 0)) && (|rules[r]| <= |parts[k]|)) && forall i: nat :: ((i < |rules[r]|) ==> (rules[r][i] == parts[k][i])))))
  {
    var part := parts[i_part_idx];
    var i_t1 := coveredPart(part, rules);
    if !(i_t1) {
      return false;
    }
    i_part_idx := i_part_idx + 1;
  }
  return true;
}
