// Generated by lsc from continuation-rule.ts

function continuationAccepted(index: int, continues: int, requests: int, ownObligations: int): bool
  requires (requests >= 0)
  requires (ownObligations >= 0)
{
  if (((continues < 1) || (continues >= index)) || (index > requests)) then
    false
  else
    (ownObligations == 0)
}

lemma continuationAccepted_ensures(index: int, continues: int, requests: int, ownObligations: int)
  requires (requests >= 0)
  requires (ownObligations >= 0)
  ensures (continuationAccepted(index, continues, requests, ownObligations) <==> ((((continues >= 1) && (continues < index)) && (index <= requests)) && (ownObligations == 0)))
{
}
