// Generated by lsc from decision-bar-rule.ts

function decisionLevel(width: int, full: int, short: int, bare: int): int
  requires (full >= short)
  requires (short >= bare)
  requires (bare >= 0)
{
  if (full <= width) then
    0
  else
    if (short <= width) then
      1
    else
      if (bare <= width) then
        2
      else
        3
}

lemma decisionLevel_ensures(width: int, full: int, short: int, bare: int)
  requires (full >= short)
  requires (short >= bare)
  requires (bare >= 0)
  ensures (decisionLevel(width, full, short, bare) >= 0)
  ensures (decisionLevel(width, full, short, bare) <= 3)
  ensures ((full <= width) ==> (decisionLevel(width, full, short, bare) == 0))
  ensures ((full > width) ==> (short <= width) ==> (decisionLevel(width, full, short, bare) == 1))
  ensures ((short > width) ==> (bare <= width) ==> (decisionLevel(width, full, short, bare) == 2))
  ensures ((bare > width) ==> (decisionLevel(width, full, short, bare) == 3))
{
}
