// Generated by lsc from default-theme-rule.ts

function usesTesotaTheme(settingsRead: bool, themeSet: bool, themeArgument: bool): bool
{
  ((settingsRead && !(themeSet)) && !(themeArgument))
}

lemma usesTesotaTheme_ensures(settingsRead: bool, themeSet: bool, themeArgument: bool)
  ensures (usesTesotaTheme(settingsRead, themeSet, themeArgument) <==> ((settingsRead && !(themeSet)) && !(themeArgument)))
{
}
