// Generated by lsc from direct-connection-rule.ts

datatype DirectConnection = blocked | connected | indeterminate

function directConnection(connectedInside: bool, refusedInside: bool, connectedFromHost: bool): DirectConnection
{
  if connectedInside then
    DirectConnection.connected
  else
    if (refusedInside && connectedFromHost) then
      DirectConnection.blocked
    else
      DirectConnection.indeterminate
}

lemma directConnection_ensures(connectedInside: bool, refusedInside: bool, connectedFromHost: bool)
  ensures (directConnection(connectedInside, refusedInside, connectedFromHost).connected? <==> connectedInside)
  ensures (directConnection(connectedInside, refusedInside, connectedFromHost).blocked? <==> ((!(connectedInside) && refusedInside) && connectedFromHost))
{
}
