// Generated by lsc from drive-release-rule.ts

function releasesDrive(leased: bool, ownerRunning: bool): bool
{
  if !(leased) then
    false
  else
    !(ownerRunning)
}

lemma releasesDrive_ensures(leased: bool, ownerRunning: bool)
  ensures (releasesDrive(leased, ownerRunning) <==> (leased && !(ownerRunning)))
{
}
