// Generated by lsc from explorer-answer.ts

datatype ExplorerTurnStatus = completed | failed | cancelled | unsettled

function isExplorerAnswer(timedOut: bool, status: ExplorerTurnStatus, answerLength: int): bool
{
  if (timedOut || (!status.completed?)) then
    false
  else
    (answerLength > 0)
}

lemma isExplorerAnswer_ensures(timedOut: bool, status: ExplorerTurnStatus, answerLength: int)
  ensures (isExplorerAnswer(timedOut, status, answerLength) == ((!(timedOut) && status.completed?) && (answerLength > 0)))
{
}

function canStartExplorer(started: int, limit: int): bool
{
  if ((started < 0) || (limit <= 0)) then
    false
  else
    (started < limit)
}

lemma canStartExplorer_ensures(started: int, limit: int)
  ensures (((started < 0) || (limit <= 0)) ==> (canStartExplorer(started, limit) == false))
  ensures ((started >= 0) ==> (limit > 0) ==> (canStartExplorer(started, limit) == (started < limit)))
{
}
