// Generated by lsc from finding-origin-rule.ts

datatype FindingOriginClaim = introduced | preexisting | unknown

datatype FileChange = none | untouched | created | deleted | modified

function checkedOrigin(claim: FindingOriginClaim, file: FileChange, readable: bool, located: bool, touched: bool, added: bool): FindingOriginClaim
{
  if claim.introduced? then
    if (file.created? || file.deleted?) then
      FindingOriginClaim.introduced
    else
      if (((file.modified? && readable) && located) && touched) then
        FindingOriginClaim.introduced
      else
        FindingOriginClaim.unknown
  else
    if claim.preexisting? then
      if file.created? then
        FindingOriginClaim.unknown
      else
        if (((file.modified? && readable) && located) && added) then
          FindingOriginClaim.unknown
        else
          FindingOriginClaim.preexisting
    else
      FindingOriginClaim.unknown
}

lemma checkedOrigin_ensures(claim: FindingOriginClaim, file: FileChange, readable: bool, located: bool, touched: bool, added: bool)
  ensures ((checkedOrigin(claim, file, readable, located, touched, added) == claim) || checkedOrigin(claim, file, readable, located, touched, added).unknown?)
  ensures (claim.unknown? ==> checkedOrigin(claim, file, readable, located, touched, added).unknown?)
  ensures (claim.introduced? ==> (file.created? || file.deleted?) ==> checkedOrigin(claim, file, readable, located, touched, added).introduced?)
  ensures (claim.introduced? ==> file.modified? ==> readable ==> located ==> touched ==> checkedOrigin(claim, file, readable, located, touched, added).introduced?)
  ensures (claim.introduced? ==> (file.none? || file.untouched?) ==> checkedOrigin(claim, file, readable, located, touched, added).unknown?)
  ensures (claim.introduced? ==> file.modified? ==> !(((readable && located) && touched)) ==> checkedOrigin(claim, file, readable, located, touched, added).unknown?)
  ensures (claim.preexisting? ==> file.created? ==> checkedOrigin(claim, file, readable, located, touched, added).unknown?)
  ensures (claim.preexisting? ==> file.modified? ==> readable ==> located ==> added ==> checkedOrigin(claim, file, readable, located, touched, added).unknown?)
  ensures (claim.preexisting? ==> (!file.created?) ==> !((((file.modified? && readable) && located) && added)) ==> checkedOrigin(claim, file, readable, located, touched, added).preexisting?)
{
}
