// Generated by lsc from footer-rule.ts

datatype Readiness = proofs_and_tests | proofs_only | tests_only | nothing

datatype EvidenceLevel = full | short | glyphs

datatype FooterLayout = FooterLayout(level: EvidenceLevel, context: bool, model: bool)

function readiness(contracts: bool, tests: bool): Readiness
{
  if contracts then
    if tests then
      Readiness.proofs_and_tests
    else
      Readiness.proofs_only
  else
    if tests then
      Readiness.tests_only
    else
      Readiness.nothing
}

lemma readiness_ensures(contracts: bool, tests: bool)
  ensures ((readiness(contracts, tests).proofs_and_tests? || readiness(contracts, tests).proofs_only?) <==> contracts)
  ensures ((readiness(contracts, tests).proofs_and_tests? || readiness(contracts, tests).tests_only?) <==> tests)
{
}

function footerLayout(width: int, full: int, short: int, glyphs: int, context: int, place: int, model: int): FooterLayout
  requires (full >= short)
  requires (short >= glyphs)
  requires (glyphs >= 0)
  requires (context >= 0)
  requires (place >= 0)
  requires (model >= 0)
{
  var showsContext := (((glyphs + 2) + context) <= width);
  var room := (if showsContext then ((width - 2) - context) else width);
  var level := (if (full <= room) then EvidenceLevel.full else (if (short <= room) then EvidenceLevel.short else EvidenceLevel.glyphs));
  FooterLayout(level, showsContext, ((showsContext && level.full?) && (((place + 2) + model) <= width)))
}

lemma footerLayout_ensures(width: int, full: int, short: int, glyphs: int, context: int, place: int, model: int)
  requires (full >= short)
  requires (short >= glyphs)
  requires (glyphs >= 0)
  requires (context >= 0)
  requires (place >= 0)
  requires (model >= 0)
  ensures (footerLayout(width, full, short, glyphs, context, place, model).context <==> (((glyphs + 2) + context) <= width))
  ensures (footerLayout(width, full, short, glyphs, context, place, model).context ==> (footerLayout(width, full, short, glyphs, context, place, model).level.full? <==> (((full + 2) + context) <= width)))
  ensures (footerLayout(width, full, short, glyphs, context, place, model).context ==> (footerLayout(width, full, short, glyphs, context, place, model).level.short? <==> ((((full + 2) + context) > width) && (((short + 2) + context) <= width))))
  ensures (!(footerLayout(width, full, short, glyphs, context, place, model).context) ==> (footerLayout(width, full, short, glyphs, context, place, model).level.full? <==> (full <= width)))
  ensures (!(footerLayout(width, full, short, glyphs, context, place, model).context) ==> (footerLayout(width, full, short, glyphs, context, place, model).level.short? <==> ((full > width) && (short <= width))))
  ensures (footerLayout(width, full, short, glyphs, context, place, model).model <==> ((footerLayout(width, full, short, glyphs, context, place, model).context && footerLayout(width, full, short, glyphs, context, place, model).level.full?) && (((place + 2) + model) <= width)))
  ensures (footerLayout(width, full, short, glyphs, context, place, model).model ==> footerLayout(width, full, short, glyphs, context, place, model).context)
{
}
