// Generated by lsc from gate-rule.ts

datatype GateVerdict = proved | send_back | no_progress | operator

datatype ProofOutcome = passed | failed | vacuous | timed_out | cancelled | not_started

function gateVerdict(outcome: ProofOutcome, repeated: bool): GateVerdict
{
  if outcome.passed? then
    GateVerdict.proved
  else
    if (outcome.failed? || outcome.vacuous?) then
      if repeated then
        GateVerdict.no_progress
      else
        GateVerdict.send_back
    else
      GateVerdict.operator
}

lemma gateVerdict_ensures(outcome: ProofOutcome, repeated: bool)
  ensures (gateVerdict(outcome, repeated).proved? <==> outcome.passed?)
  ensures (gateVerdict(outcome, repeated).send_back? <==> ((outcome.failed? || outcome.vacuous?) && !(repeated)))
  ensures (gateVerdict(outcome, repeated).no_progress? <==> ((outcome.failed? || outcome.vacuous?) && repeated))
  ensures (gateVerdict(outcome, repeated).operator? <==> ((outcome.not_started? || outcome.timed_out?) || outcome.cancelled?))
{
}

method keepsWorking(verdicts: seq<GateVerdict>) returns (res: bool)
  ensures (res <==> exists k: nat :: ((k < |verdicts|) && verdicts[k].send_back?))
{
  var k := 0;
  while (k < |verdicts|)
    invariant (0 <= k)
    invariant (k <= |verdicts|)
    invariant forall j: nat :: ((j < k) ==> (!verdicts[j].send_back?))
  {
    if verdicts[k].send_back? {
      return true;
    }
    k := (k + 1);
  }
  return false;
}
