// Generated by lsc from gate-rule.ts

datatype GateVerdict = proved | send_back | no_progress | operator

datatype ProofOutcome = passed | failed | vacuous | timed_out | cancelled | not_started

method gateVerdict(outcome: ProofOutcome, failure: string, sent: seq<string>) returns (res: GateVerdict)
  ensures (res.proved? <==> outcome.passed?)
  ensures (res.send_back? <==> ((outcome.failed? || outcome.vacuous?) && !(exists k: nat :: ((k < |sent|) && (sent[k] == failure)))))
  ensures (res.no_progress? <==> ((outcome.failed? || outcome.vacuous?) && exists k: nat :: ((k < |sent|) && (sent[k] == failure))))
  ensures (res.operator? <==> ((outcome.not_started? || outcome.timed_out?) || outcome.cancelled?))
{
  if outcome.passed? {
    return GateVerdict.proved;
  }
  if ((!outcome.failed?) && (!outcome.vacuous?)) {
    return GateVerdict.operator;
  }
  var k := 0;
  while (k < |sent|)
    invariant (0 <= k)
    invariant (k <= |sent|)
    invariant forall j: nat :: ((j < k) ==> (sent[j] != failure))
  {
    if (sent[k] == failure) {
      return GateVerdict.no_progress;
    }
    k := (k + 1);
  }
  return GateVerdict.send_back;
}

method keepsWorking(verdicts: seq<GateVerdict>) returns (res: bool)
  ensures (res <==> exists k: nat :: ((k < |verdicts|) && verdicts[k].send_back?))
{
  var k := 0;
  while (k < |verdicts|)
    invariant (0 <= k)
    invariant (k <= |verdicts|)
    invariant forall j: nat :: ((j < k) ==> (!verdicts[j].send_back?))
  {
    if verdicts[k].send_back? {
      return true;
    }
    k := (k + 1);
  }
  return false;
}
