// Generated by lsc from helper-answer.ts

datatype HelperTurnStatus = completed | failed | cancelled | unsettled

function isHelperAnswer(timedOut: bool, status: HelperTurnStatus, answerLength: int): bool
{
  if (timedOut || (!status.completed?)) then
    false
  else
    (answerLength > 0)
}

lemma isHelperAnswer_ensures(timedOut: bool, status: HelperTurnStatus, answerLength: int)
  ensures (isHelperAnswer(timedOut, status, answerLength) == ((!(timedOut) && status.completed?) && (answerLength > 0)))
{
}
