// Generated by lsc from helper-answer.ts

datatype HelperTurnStatus = completed | failed | cancelled | unsettled | timed_out

function isHelperAnswer(status: HelperTurnStatus, answerLength: int): bool
{
  if (!status.completed?) then
    false
  else
    (answerLength > 0)
}

lemma isHelperAnswer_ensures(status: HelperTurnStatus, answerLength: int)
  ensures (isHelperAnswer(status, answerLength) == (status.completed? && (answerLength > 0)))
{
}

function canStartHelper(started: int, limit: int): bool
{
  if ((started < 0) || (limit <= 0)) then
    false
  else
    (started < limit)
}

lemma canStartHelper_ensures(started: int, limit: int)
  ensures (((started < 0) || (limit <= 0)) ==> (canStartHelper(started, limit) == false))
  ensures ((started >= 0) ==> (limit > 0) ==> (canStartHelper(started, limit) == (started < limit)))
{
}
