// Generated by lsc from invocation-admission.ts

datatype InvocationPhase = inference | verification

datatype InvocationAdmission = allow | deny

function canAdmitInvocation(phase: InvocationPhase, used: int, limit: int): InvocationAdmission
{
  if ((!phase.inference?) && (!phase.verification?)) then
    InvocationAdmission.deny
  else
    if ((used < 0) || (limit <= 0)) then
      InvocationAdmission.deny
    else
      if (used < limit) then
        InvocationAdmission.allow
      else
        InvocationAdmission.deny
}

lemma canAdmitInvocation_ensures(phase: InvocationPhase, used: int, limit: int)
  ensures (((used < 0) || (limit <= 0)) ==> canAdmitInvocation(phase, used, limit).deny?)
  ensures ((used >= limit) ==> canAdmitInvocation(phase, used, limit).deny?)
  ensures ((used >= 0) ==> (limit > 0) ==> (used < limit) ==> canAdmitInvocation(phase, used, limit).allow?)
{
}
