// Generated by lsc from judge-independence.ts

datatype JudgeIndependence = same_model | same_lab | independent

function judgeIndependence(sameModel: bool, sameLab: bool): JudgeIndependence
  requires (!(sameModel) || sameLab)
{
  if sameModel then
    JudgeIndependence.same_model
  else
    if sameLab then
      JudgeIndependence.same_lab
    else
      JudgeIndependence.independent
}

lemma judgeIndependence_ensures(sameModel: bool, sameLab: bool)
  requires (!(sameModel) || sameLab)
  ensures (sameModel ==> judgeIndependence(sameModel, sameLab).same_model?)
  ensures (!(sameModel) ==> sameLab ==> judgeIndependence(sameModel, sameLab).same_lab?)
  ensures (!(sameLab) ==> judgeIndependence(sameModel, sameLab).independent?)
{
}
