// Generated by lsc from model-switch.ts

datatype ModelSwitch = unchanged_ | in_place | new_conversation

function modelSwitch(sameModel: bool, sameEngine: bool): ModelSwitch
{
  if sameModel then
    ModelSwitch.unchanged_
  else
    if sameEngine then
      ModelSwitch.in_place
    else
      ModelSwitch.new_conversation
}

lemma modelSwitch_ensures(sameModel: bool, sameEngine: bool)
  ensures (sameModel ==> modelSwitch(sameModel, sameEngine).unchanged_?)
  ensures (!(sameModel) ==> sameEngine ==> modelSwitch(sameModel, sameEngine).in_place?)
  ensures (!(sameModel) ==> !(sameEngine) ==> modelSwitch(sameModel, sameEngine).new_conversation?)
{
}

function needsBrief(resumed: bool, hasHistory: bool): bool
{
  (!(resumed) && hasHistory)
}

lemma needsBrief_ensures(resumed: bool, hasHistory: bool)
  ensures (needsBrief(resumed, hasHistory) <==> (!(resumed) && hasHistory))
{
}
