// Generated by lsc from mutation-rule.ts

datatype MutantFinding = rejected | survived | inconclusive

datatype ProofOutcome = passed | failed | vacuous | timed_out | cancelled | not_started

function mutantFinding(outcome: ProofOutcome): MutantFinding
{
  if outcome.failed? then
    MutantFinding.rejected
  else
    if outcome.passed? then
      MutantFinding.survived
    else
      MutantFinding.inconclusive
}

lemma mutantFinding_ensures(outcome: ProofOutcome)
  ensures (mutantFinding(outcome).rejected? <==> outcome.failed?)
  ensures (mutantFinding(outcome).survived? <==> outcome.passed?)
  ensures (mutantFinding(outcome).inconclusive? <==> ((!outcome.failed?) && (!outcome.passed?)))
{
}

function equivalentMutant(outcome: ProofOutcome): bool
{
  outcome.passed?
}

lemma equivalentMutant_ensures(outcome: ProofOutcome)
  ensures (equivalentMutant(outcome) <==> outcome.passed?)
{
}
