// Generated by lsc from obligation-outcome.ts

datatype ObligationStatus = met | partial | unmet | uncertain

datatype ObligationStanding = confirmed | refuted | unsettled | untested

datatype ObligationOutcome = uncertain | held | not_held

function obligationOutcome(status: ObligationStatus, standing: ObligationStanding): ObligationOutcome
{
  if status.met? then
    ObligationOutcome.held
  else
    if status.uncertain? then
      ObligationOutcome.uncertain
    else
      if standing.confirmed? then
        ObligationOutcome.not_held
      else
        if standing.refuted? then
          ObligationOutcome.held
        else
          ObligationOutcome.uncertain
}

lemma obligationOutcome_ensures(status: ObligationStatus, standing: ObligationStanding)
  ensures (obligationOutcome(status, standing).not_held? <==> ((status.partial? || status.unmet?) && standing.confirmed?))
  ensures (obligationOutcome(status, standing).held? <==> (status.met? || ((status.partial? || status.unmet?) && standing.refuted?)))
{
}
