// Generated by lsc from permission-mode.ts

datatype PermissionMode = read_only | accept_edits | full_access

datatype CommandPlace = sandbox | computer

function editsAllowed(mode: PermissionMode): bool
{
  (!mode.read_only?)
}

lemma editsAllowed_ensures(mode: PermissionMode)
  ensures (editsAllowed(mode) <==> (!mode.read_only?))
{
}

function commandPlace(mode: PermissionMode, sandboxed: bool): CommandPlace
{
  if (mode.full_access? || !(sandboxed)) then
    CommandPlace.computer
  else
    CommandPlace.sandbox
}

lemma commandPlace_ensures(mode: PermissionMode, sandboxed: bool)
  ensures (commandPlace(mode, sandboxed).computer? <==> (mode.full_access? || !(sandboxed)))
{
}

function commandRunsWithoutAsking(mode: PermissionMode, place: CommandPlace, allowedByRule: bool): bool
{
  (mode.full_access? || (if mode.read_only? then false else (place.sandbox? || allowedByRule)))
}

lemma commandRunsWithoutAsking_ensures(mode: PermissionMode, place: CommandPlace, allowedByRule: bool)
  ensures (commandRunsWithoutAsking(mode, place, allowedByRule) <==> (mode.full_access? || (mode.accept_edits? && (place.sandbox? || allowedByRule))))
{
}

function offersRule(mode: PermissionMode): bool
{
  mode.accept_edits?
}

lemma offersRule_ensures(mode: PermissionMode)
  ensures (offersRule(mode) <==> mode.accept_edits?)
{
}

function nextMode(mode: PermissionMode): PermissionMode
{
  if mode.read_only? then
    PermissionMode.accept_edits
  else
    if mode.accept_edits? then
      PermissionMode.full_access
    else
      PermissionMode.read_only
}

lemma nextMode_ensures(mode: PermissionMode)
  ensures (mode.read_only? ==> nextMode(mode).accept_edits?)
  ensures (mode.accept_edits? ==> nextMode(mode).full_access?)
  ensures (mode.full_access? ==> nextMode(mode).read_only?)
{
}

function needsConfirmation(next: PermissionMode, confirmed: bool): bool
{
  (next.full_access? && !(confirmed))
}

lemma needsConfirmation_ensures(next: PermissionMode, confirmed: bool)
  ensures (needsConfirmation(next, confirmed) <==> (next.full_access? && !(confirmed)))
{
}
