// Generated by lsc from pi-version-rule.ts

function versionAtLeast(major: int, minor: int, patch: int, minMajor: int, minMinor: int, minPatch: int): bool
  requires (major >= 0)
  requires (minor >= 0)
  requires (patch >= 0)
  requires (minMajor >= 0)
  requires (minMinor >= 0)
  requires (minPatch >= 0)
{
  if (major != minMajor) then
    (major > minMajor)
  else
    if (minor != minMinor) then
      (minor > minMinor)
    else
      (patch >= minPatch)
}

lemma versionAtLeast_ensures(major: int, minor: int, patch: int, minMajor: int, minMinor: int, minPatch: int)
  requires (major >= 0)
  requires (minor >= 0)
  requires (patch >= 0)
  requires (minMajor >= 0)
  requires (minMinor >= 0)
  requires (minPatch >= 0)
  ensures (versionAtLeast(major, minor, patch, minMajor, minMinor, minPatch) <==> ((major > minMajor) || ((major == minMajor) && ((minor > minMinor) || ((minor == minMinor) && (patch >= minPatch))))))
{
}
