// Generated by lsc from plan-rule.ts

function planAccepted(steps: int, inProgress: int, unexplainedBlocked: int): bool
  requires (steps >= 0)
  requires (inProgress >= 0)
  requires (unexplainedBlocked >= 0)
{
  if ((steps < 1) || (steps > 20)) then
    false
  else
    ((inProgress <= 1) && (unexplainedBlocked == 0))
}

lemma planAccepted_ensures(steps: int, inProgress: int, unexplainedBlocked: int)
  requires (steps >= 0)
  requires (inProgress >= 0)
  requires (unexplainedBlocked >= 0)
  ensures (planAccepted(steps, inProgress, unexplainedBlocked) <==> ((((steps >= 1) && (steps <= 20)) && (inProgress <= 1)) && (unexplainedBlocked == 0)))
{
}
