// Generated by lsc from project-rule.ts

function below(folder: string, other: string): bool
{
  ((folder != other) && ((folder == "") || (|other| >= |(folder + "/")| && other[..|(folder + "/")|] == (folder + "/"))))
}

lemma below_ensures(folder: string, other: string)
  ensures (below(folder, other) <==> ((folder != other) && ((folder == "") || (|other| >= |(folder + "/")| && other[..|(folder + "/")|] == (folder + "/")))))
  ensures ((folder == other) ==> !(below(folder, other)))
  ensures ((folder == "") ==> (other != "") ==> below(folder, other))
{
}

function builtIn(markers: seq<string>, entries: seq<string>): bool
{
  (exists marker :: marker in markers && (if (|marker| >= |"*"| && marker[..|"*"|] == "*") then (exists name :: name in entries && (|name| >= |marker[1..]| && name[|name|-|marker[1..]|..] == marker[1..])) else (marker in entries)))
}

lemma builtIn_ensures(markers: seq<string>, entries: seq<string>)
  ensures (builtIn(markers, entries) <==> exists m: nat :: ((m < |markers|) && exists n: nat :: ((n < |entries|) && (if (|markers[m]| >= |"*"| && markers[m][..|"*"|] == "*") then (|entries[n]| >= |markers[m][1..]| && entries[n][|entries[n]|-|markers[m][1..]|..] == markers[m][1..]) else (entries[n] == markers[m])))))
{
}

function pinnedIn(markers: seq<string>, versionFiles: seq<string>, entries: seq<string>): bool
{
  (!(builtIn(markers, entries)) && (exists file :: file in versionFiles && (file in entries)))
}

lemma pinnedIn_ensures(markers: seq<string>, versionFiles: seq<string>, entries: seq<string>)
  ensures (pinnedIn(markers, versionFiles, entries) <==> (!(builtIn(markers, entries)) && exists n: nat :: ((n < |versionFiles|) && (versionFiles[n] in entries))))
{
}

function keepsProjectKind(versionOnly: bool, descendantBuild: bool): bool
{
  (!(versionOnly) || !(descendantBuild))
}

lemma keepsProjectKind_ensures(versionOnly: bool, descendantBuild: bool)
  ensures (keepsProjectKind(versionOnly, descendantBuild) <==> (!(versionOnly) || !(descendantBuild)))
{
}

function versionSource(local: string, ancestorPin: bool): string
{
  if ((local != "pin") && ancestorPin) then
    "ancestor"
  else
    "local"
}

lemma versionSource_ensures(local: string, ancestorPin: bool)
  ensures ((versionSource(local, ancestorPin) == "ancestor") <==> ((local != "pin") && ancestorPin))
  ensures ((versionSource(local, ancestorPin) == "local") <==> ((local == "pin") || !(ancestorPin)))
{
}
