// Generated by lsc from project-rule.ts

function below(folder: string, other: string): bool
{
  ((folder != other) && ((folder == "") || (|other| >= |(folder + "/")| && other[..|(folder + "/")|] == (folder + "/"))))
}

lemma below_ensures(folder: string, other: string)
  ensures (below(folder, other) <==> ((folder != other) && ((folder == "") || (|other| >= |(folder + "/")| && other[..|(folder + "/")|] == (folder + "/")))))
  ensures ((folder == other) ==> !(below(folder, other)))
  ensures ((folder == "") ==> (other != "") ==> below(folder, other))
{
}

function builtIn(markers: seq<string>, entries: seq<string>): bool
{
  (exists marker :: marker in markers && (if (|marker| >= |"*"| && marker[..|"*"|] == "*") then (exists name :: name in entries && (|name| >= |marker[1..]| && name[|name|-|marker[1..]|..] == marker[1..])) else (marker in entries)))
}

lemma builtIn_ensures(markers: seq<string>, entries: seq<string>)
  ensures (builtIn(markers, entries) <==> exists m: nat :: ((m < |markers|) && exists n: nat :: ((n < |entries|) && (if (|markers[m]| >= |"*"| && markers[m][..|"*"|] == "*") then (|entries[n]| >= |markers[m][1..]| && entries[n][|entries[n]|-|markers[m][1..]|..] == markers[m][1..]) else (entries[n] == markers[m])))))
{
}

function pinnedIn(markers: seq<string>, versionFiles: seq<string>, entries: seq<string>): bool
{
  (!(builtIn(markers, entries)) && (exists file :: file in versionFiles && (file in entries)))
}

lemma pinnedIn_ensures(markers: seq<string>, versionFiles: seq<string>, entries: seq<string>)
  ensures (pinnedIn(markers, versionFiles, entries) <==> (!(builtIn(markers, entries)) && exists n: nat :: ((n < |versionFiles|) && (versionFiles[n] in entries))))
{
}

function keepsProjectKind(versionOnly: bool, descendantBuild: bool): bool
{
  (!(versionOnly) || !(descendantBuild))
}

lemma keepsProjectKind_ensures(versionOnly: bool, descendantBuild: bool)
  ensures (keepsProjectKind(versionOnly, descendantBuild) <==> (!(versionOnly) || !(descendantBuild)))
{
}

function holds(folder: string, path: string): bool
{
  ((folder == "") || (|path| >= |(folder + "/")| && path[..|(folder + "/")|] == (folder + "/")))
}

lemma holds_ensures(folder: string, path: string)
  ensures (holds(folder, path) <==> ((folder == "") || (|path| >= |(folder + "/")| && path[..|(folder + "/")|] == (folder + "/"))))
{
}

method owner(folders: seq<string>, path: string) returns (res: int)
  ensures (res >= -1)
  ensures (res < |folders|)
  ensures ((res == -1) <==> forall k: nat :: ((k < |folders|) ==> !(holds(folders[k], path))))
  ensures ((res >= 0) ==> holds(folders[res], path))
  ensures ((res >= 0) ==> forall k: nat :: ((k < |folders|) ==> holds(folders[k], path) ==> (|folders[k]| <= |folders[res]|)))
{
  var found := -1;
  var k := 0;
  while (k < |folders|)
    invariant (0 <= k)
    invariant (k <= |folders|)
    invariant (found >= -1)
    invariant (found < k)
    invariant ((found == -1) <==> forall j: nat :: ((j < k) ==> !(holds(folders[j], path))))
    invariant ((found >= 0) ==> holds(folders[found], path))
    invariant ((found >= 0) ==> forall j: nat :: ((j < k) ==> holds(folders[j], path) ==> (|folders[j]| <= |folders[found]|)))
  {
    var i_t0 := holds(folders[k], path);
    if (i_t0 && ((found == -1) || (|folders[k]| > |folders[found]|))) {
      found := k;
    }
    k := (k + 1);
  }
  return found;
}
