// Generated by lsc from proof-cover-rule.ts

method proofCovered(line: int, starts: seq<int>, ends: seq<int>, proved: seq<bool>, narrowed: seq<bool>) returns (res: bool)
  requires (|starts| == |ends|)
  requires (|starts| == |proved|)
  requires (|starts| == |narrowed|)
  ensures (res <==> exists k: nat :: (((((k < |starts|) && (starts[k] <= line)) && (line <= ends[k])) && proved[k]) && !(narrowed[k])))
{
  var k := 0;
  while (k < |starts|)
    invariant (0 <= k)
    invariant (k <= |starts|)
    invariant forall j: nat :: ((j < k) ==> !(((((starts[j] <= line) && (line <= ends[j])) && proved[j]) && !(narrowed[j]))))
  {
    if ((((starts[k] <= line) && (line <= ends[k])) && proved[k]) && !(narrowed[k])) {
      return true;
    }
    k := (k + 1);
  }
  return false;
}
