// Generated by lsc from proof-outcome-rule.ts

datatype ProofOutcome = passed | failed | timed_out | cancelled | not_started

function proofOutcome(cancelled: bool, timedOut: bool, started: bool, regenerated: bool, checkExit: int, verified: int): ProofOutcome
{
  if cancelled then
    ProofOutcome.cancelled
  else
    if timedOut then
      ProofOutcome.timed_out
    else
      if !(started) then
        ProofOutcome.not_started
      else
        if (!(regenerated) || (checkExit != 0)) then
          ProofOutcome.failed
        else
          if (verified > 0) then
            ProofOutcome.passed
          else
            ProofOutcome.not_started
}

lemma proofOutcome_ensures(cancelled: bool, timedOut: bool, started: bool, regenerated: bool, checkExit: int, verified: int)
  ensures (proofOutcome(cancelled, timedOut, started, regenerated, checkExit, verified).passed? <==> (((((!(cancelled) && !(timedOut)) && started) && regenerated) && (checkExit == 0)) && (verified > 0)))
  ensures (cancelled ==> proofOutcome(cancelled, timedOut, started, regenerated, checkExit, verified).cancelled?)
  ensures (!(cancelled) ==> timedOut ==> proofOutcome(cancelled, timedOut, started, regenerated, checkExit, verified).timed_out?)
  ensures (proofOutcome(cancelled, timedOut, started, regenerated, checkExit, verified).failed? ==> (started && (!(regenerated) || (checkExit != 0))))
{
}
