// Generated by lsc from question-rule.ts

method questionShortcut(keys: seq<string>, data: string) returns (res: int)
  ensures (-1 <= res)
  ensures (res < |keys|)
  ensures ((|data| != 1) ==> (res == -1))
  ensures ((res >= 0) ==> ((|data| == 1) && (keys[res] == data)))
  ensures ((res >= 0) ==> forall i: nat :: ((i < res) ==> (keys[i] != data)))
  ensures ((|data| == 1) ==> (res == -1) ==> forall i: nat :: ((i < |keys|) ==> (keys[i] != data)))
{
  if (|data| != 1) {
    return -1;
  }
  var i := 0;
  while (i < |keys|)
    invariant (0 <= i)
    invariant (i <= |keys|)
    invariant forall j: nat :: ((j < i) ==> (keys[j] != data))
  {
    if (keys[i] == data) {
      return i;
    }
    i := (i + 1);
  }
  return -1;
}
