// Generated by lsc from quote-rule.ts

function quoteKept(found: bool, length: int, kept: int, lengthLimit: int, countLimit: int): bool
  requires (length >= 0)
  requires (kept >= 0)
{
  if (!(found) || (length < 1)) then
    false
  else
    ((length <= lengthLimit) && (kept < countLimit))
}

lemma quoteKept_ensures(found: bool, length: int, kept: int, lengthLimit: int, countLimit: int)
  requires (length >= 0)
  requires (kept >= 0)
  ensures (quoteKept(found, length, kept, lengthLimit, countLimit) <==> (((found && (length >= 1)) && (length <= lengthLimit)) && (kept < countLimit)))
{
}
