// Generated by lsc from range-rule.ts

datatype Range = Range(start: int, end: int)

lemma SortedLe(numbers: seq<int>, a: nat, b: nat)
  requires a <= b < |numbers|
  requires forall i: nat :: i + 1 < |numbers| ==> numbers[i] < numbers[i + 1]
  ensures numbers[a] <= numbers[b]
  decreases b - a
{
  if a < b {
    SortedLe(numbers, a, b - 1);
    assert numbers[b - 1] < numbers[b];
  }
}

lemma AppendRangeMembership(found: seq<Range>, numbers: seq<int>, run: nat, k: nat, start: int, end: int)
  requires run <= k <= |numbers|
  requires forall x: int :: (exists r: nat :: r < |found| && found[r].start <= x && x <= found[r].end) <==> x in numbers[0..run]
  requires forall x: int :: (start <= x && x <= end) <==> x in numbers[run..k]
  ensures forall x: int :: (exists r: nat :: r < |found + [Range(start, end)]| && (found + [Range(start, end)])[r].start <= x && x <= (found + [Range(start, end)])[r].end) <==> x in numbers[0..k]
{
  assert numbers[0..k] == numbers[0..run] + numbers[run..k];
  assert forall x: int :: (exists r: nat :: r < |found + [Range(start, end)]| && (found + [Range(start, end)])[r].start <= x && x <= (found + [Range(start, end)])[r].end) <==> x in numbers[0..k] by {
    forall x: int
      ensures (exists r: nat :: r < |found + [Range(start, end)]| && (found + [Range(start, end)])[r].start <= x && x <= (found + [Range(start, end)])[r].end) <==> x in numbers[0..k]
    {
      if exists r: nat :: r < |found + [Range(start, end)]| && (found + [Range(start, end)])[r].start <= x && x <= (found + [Range(start, end)])[r].end {
        var r: nat :| r < |found + [Range(start, end)]| && (found + [Range(start, end)])[r].start <= x && x <= (found + [Range(start, end)])[r].end;
        assert r < |found + [Range(start, end)]|;
        if r < |found| {
          assert r < |found|;
          assert found[r] == (found + [Range(start, end)])[r];
          assert found[r].start <= x && x <= found[r].end;
          assert exists q: nat :: q < |found| && found[q].start <= x && x <= found[q].end;
          assert x in numbers[0..run];
          assert x in numbers[0..k];
        } else {
          assert r == |found|;
          assert (found + [Range(start, end)])[r] == Range(start, end);
          assert x in numbers[run..k];
          assert x in numbers[0..k];
        }
      } else if x in numbers[0..k] {
        assert x in numbers[0..run] || x in numbers[run..k];
        if x in numbers[0..run] {
          assert exists r: nat :: r < |found| && found[r].start <= x && x <= found[r].end;
          var r: nat :| r < |found| && found[r].start <= x && x <= found[r].end;
          assert r < |found + [Range(start, end)]|;
          assert found[r] == (found + [Range(start, end)])[r];
        } else {
          assert x in numbers[run..k];
          assert start <= x && x <= end;
          assert |found| < |found + [Range(start, end)]|;
          assert (found + [Range(start, end)])[|found|] == Range(start, end);
        }
      }
    }
  }
}

lemma ConsecutiveSlice(numbers: seq<int>, run: nat, k: nat)
  requires run < k <= |numbers|
  requires forall i: nat :: run <= i && i + 1 < k ==> numbers[i] + 1 == numbers[i + 1]
  requires forall i: nat :: i + 1 < |numbers| ==> numbers[i] < numbers[i + 1]
  ensures forall x: int :: (numbers[run] <= x && x <= numbers[k - 1]) <==> x in numbers[run..k]
  decreases k - run
{
  if k == run + 1 {
    assert numbers[run..k] == [numbers[run]];
    assert forall x: int :: (numbers[run] <= x && x <= numbers[k - 1]) <==> x in numbers[run..k] by {
      forall x: int
        ensures (numbers[run] <= x && x <= numbers[k - 1]) <==> x in numbers[run..k]
      {
        assert k - 1 == run;
        if numbers[run] <= x && x <= numbers[k - 1] {
          assert x == numbers[run];
        } else if x in numbers[run..k] {
          assert x in [numbers[run]];
          assert x == numbers[run];
        }
        assert (numbers[run] <= x && x <= numbers[k - 1]) ==> x in numbers[run..k];
        assert x in numbers[run..k] ==> (numbers[run] <= x && x <= numbers[k - 1]);
      }
    }
  } else {
    ConsecutiveSlice(numbers, run, k - 1);
    assert numbers[k - 2] + 1 == numbers[k - 1];
    assert forall x: int :: (numbers[run] <= x && x <= numbers[k - 1]) <==> x in numbers[run..k] by {
      forall x: int
        ensures (numbers[run] <= x && x <= numbers[k - 1]) <==> x in numbers[run..k]
      {
        if numbers[run] <= x && x <= numbers[k - 1] {
          if x == numbers[k - 1] {
            assert x in [numbers[k - 1]];
            assert numbers[run..k] == numbers[run..k - 1] + [numbers[k - 1]];
            assert x in numbers[run..k];
          } else {
            assert x < numbers[k - 1];
            assert x <= numbers[k - 2];
            assert x in numbers[run..k - 1];
            assert numbers[run..k] == numbers[run..k - 1] + [numbers[k - 1]];
            assert x in numbers[run..k];
          }
        } else if x in numbers[run..k] {
          assert numbers[run..k] == numbers[run..k - 1] + [numbers[k - 1]];
          assert x in numbers[run..k - 1] || x in [numbers[k - 1]];
          if x in numbers[run..k - 1] {
            assert numbers[run] <= x && x <= numbers[k - 2];
            assert x <= numbers[k - 1];
          } else {
            assert x in [numbers[k - 1]];
            assert x == numbers[k - 1];
          }
        }
        assert (numbers[run] <= x && x <= numbers[k - 1]) ==> x in numbers[run..k];
        if x in numbers[run..k] {
          assert numbers[run..k] == numbers[run..k - 1] + [numbers[k - 1]];
          assert x in numbers[run..k - 1] || x in [numbers[k - 1]];
          if x in numbers[run..k - 1] {
            assert numbers[run] <= x && x <= numbers[k - 2];
            assert x <= numbers[k - 1];
          } else {
            assert x in [numbers[k - 1]];
            assert x == numbers[k - 1];
            SortedLe(numbers, run, k - 1);
          }
          assert numbers[run] <= x && x <= numbers[k - 1];
        }
        assert x in numbers[run..k] ==> (numbers[run] <= x && x <= numbers[k - 1]);
      }
    }
  }
}

method ranges(numbers: seq<int>) returns (res: seq<Range>)
  requires forall i: nat :: (((i + 1) < |numbers|) ==> (numbers[i] < numbers[(i + 1)]))
  ensures forall r: nat :: ((r < |res|) ==> (res[r].start <= res[r].end))
  ensures forall r: nat :: (((r + 1) < |res|) ==> ((res[r].end + 1) < res[(r + 1)].start))
  ensures forall x: int :: ((exists r: nat :: (((r < |res|) && (res[r].start <= x)) && (x <= res[r].end))) <==> (x in numbers))
{
  var found: seq<Range> := [];
  if (|numbers| == 0) {
    return found;
  }
  var start := numbers[0];
  var end := numbers[0];
  var i_run := 0;
  var k := 1;
  while (k < |numbers|)
    invariant (1 <= k)
    invariant (k <= |numbers|)
    invariant (0 <= i_run)
    invariant (i_run < k)
    invariant (start == numbers[i_run])
    invariant (end == numbers[(k - 1)])
    invariant (start <= end)
    invariant forall i: nat :: (((i + 1) < |numbers|) ==> (numbers[i] < numbers[(i + 1)]))
    invariant forall i: nat :: ((i_run <= i) ==> ((i + 1) < k) ==> ((numbers[i] + 1) == numbers[(i + 1)]))
    invariant forall r: nat :: ((r < |found|) ==> (found[r].start <= found[r].end))
    invariant forall r: nat :: (((r + 1) < |found|) ==> ((found[r].end + 1) < found[(r + 1)].start))
    invariant ((|found| > 0) ==> ((found[(|found| - 1)].end + 1) < start))
    invariant forall x: int :: ((exists r: nat :: (((r < |found|) && (found[r].start <= x)) && (x <= found[r].end))) <==> (x in numbers[0..i_run]))
    invariant forall x: int :: (((start <= x) && (x <= end)) <==> (x in numbers[i_run..k]))
  {
    var number := numbers[k];
    if ((end + 1) == number) {
      end := number;
    } else {
      assert (end < number);
      assert ((end + 1) < number);
      ConsecutiveSlice(numbers, i_run as nat, k as nat);
      AppendRangeMembership(found, numbers, i_run as nat, k as nat, start, end);
      found := (found + [Range(start, end)]);
      start := number;
      end := number;
      i_run := k;
    }
    k := (k + 1);
    ConsecutiveSlice(numbers, i_run as nat, k as nat);
  }
  ConsecutiveSlice(numbers, i_run as nat, k as nat);
  AppendRangeMembership(found, numbers, i_run as nat, k as nat, start, end);
  found := (found + [Range(start, end)]);
  assert numbers[0..k] == numbers;
  assert forall x: int :: ((exists r: nat :: (((r < |found|) && (found[r].start <= x)) && (x <= found[r].end))) <==> (x in numbers));
  return found;
}
