// Generated by lsc from recheck-rule.ts

datatype Recheck = resolved | present | unchecked

datatype RecheckVerdict = resolved | unresolved | undetermined | none

function recheckOf(correctionChanged: bool, verdict: RecheckVerdict): Recheck
{
  if !(correctionChanged) then
    Recheck.present
  else
    if verdict.resolved? then
      Recheck.resolved
    else
      if verdict.unresolved? then
        Recheck.present
      else
        Recheck.unchecked
}

lemma recheckOf_ensures(correctionChanged: bool, verdict: RecheckVerdict)
  ensures (!(correctionChanged) ==> recheckOf(correctionChanged, verdict).present?)
  ensures (recheckOf(correctionChanged, verdict).resolved? ==> (correctionChanged && verdict.resolved?))
  ensures (correctionChanged ==> verdict.resolved? ==> recheckOf(correctionChanged, verdict).resolved?)
  ensures (correctionChanged ==> verdict.unresolved? ==> recheckOf(correctionChanged, verdict).present?)
  ensures (correctionChanged ==> (verdict.undetermined? || verdict.none?) ==> recheckOf(correctionChanged, verdict).unchecked?)
{
}
