// Generated by lsc from review-action-rule.ts

datatype ReviewAction = agent | operator | context

datatype ActionOrigin = introduced | preexisting | unknown

datatype ActionDisposition = operator | fixable

datatype ActionStanding = confirmed | refuted | unsettled | untested

datatype ActionVerifier = command | oxlint | lemmascript

datatype ActionOutcome = passed | failed | timed_out | cancelled | not_started | unconfirmed | changed_files

datatype ActionCheckOrigin = introduced | preexisting | unknown | absent

datatype ActionObligation = held | not_held | uncertain

datatype ObligationDisposition = operator | fixable

function findingAction(origin: ActionOrigin, disposition: ActionDisposition, standing: ActionStanding, duplicate: bool): ReviewAction
{
  if ((duplicate || standing.refuted?) || origin.preexisting?) then
    ReviewAction.context
  else
    if ((standing.confirmed? && origin.introduced?) && disposition.fixable?) then
      ReviewAction.agent
    else
      ReviewAction.operator
}

lemma findingAction_ensures(origin: ActionOrigin, disposition: ActionDisposition, standing: ActionStanding, duplicate: bool)
  ensures (findingAction(origin, disposition, standing, duplicate).agent? <==> (((!(duplicate) && standing.confirmed?) && origin.introduced?) && disposition.fixable?))
  ensures (findingAction(origin, disposition, standing, duplicate).context? <==> ((duplicate || standing.refuted?) || origin.preexisting?))
{
}

function checkAction(verifier: ActionVerifier, outcome: ActionOutcome, origin: ActionCheckOrigin): ReviewAction
{
  if outcome.passed? then
    ReviewAction.context
  else
    if ((!outcome.failed?) && (!outcome.timed_out?)) then
      ReviewAction.operator
    else
      if ((!verifier.command?) || origin.introduced?) then
        ReviewAction.agent
      else
        if origin.preexisting? then
          ReviewAction.context
        else
          ReviewAction.operator
}

lemma checkAction_ensures(verifier: ActionVerifier, outcome: ActionOutcome, origin: ActionCheckOrigin)
  ensures (outcome.passed? ==> checkAction(verifier, outcome, origin).context?)
  ensures (checkAction(verifier, outcome, origin).agent? <==> ((outcome.failed? || outcome.timed_out?) && ((!verifier.command?) || origin.introduced?)))
  ensures (checkAction(verifier, outcome, origin).context? <==> (outcome.passed? || (((outcome.failed? || outcome.timed_out?) && verifier.command?) && origin.preexisting?)))
{
}

function obligationAction(outcome: ActionObligation, disposition: ObligationDisposition): ReviewAction
{
  if outcome.not_held? then
    if disposition.fixable? then
      ReviewAction.agent
    else
      ReviewAction.operator
  else
    if outcome.uncertain? then
      ReviewAction.operator
    else
      ReviewAction.context
}

lemma obligationAction_ensures(outcome: ActionObligation, disposition: ObligationDisposition)
  ensures (obligationAction(outcome, disposition).agent? <==> (outcome.not_held? && disposition.fixable?))
  ensures (obligationAction(outcome, disposition).operator? <==> (outcome.uncertain? || (outcome.not_held? && disposition.operator?)))
  ensures (obligationAction(outcome, disposition).context? <==> outcome.held?)
{
}
