// Generated by lsc from review-start-rule.ts

function candidateStart(turns: int, reviewedEnd: int, reviewedStart: int): int
  requires (turns >= 1)
  requires (reviewedEnd >= -1)
  requires (reviewedEnd < turns)
  requires (reviewedStart >= -1)
  requires (reviewedStart < turns)
{
  if ((reviewedEnd >= 0) && (reviewedEnd < (turns - 1))) then
    (reviewedEnd + 1)
  else
    if (reviewedStart >= 0) then
      reviewedStart
    else
      0
}

lemma candidateStart_ensures(turns: int, reviewedEnd: int, reviewedStart: int)
  requires (turns >= 1)
  requires (reviewedEnd >= -1)
  requires (reviewedEnd < turns)
  requires (reviewedStart >= -1)
  requires (reviewedStart < turns)
  ensures (candidateStart(turns, reviewedEnd, reviewedStart) >= 0)
  ensures (candidateStart(turns, reviewedEnd, reviewedStart) < turns)
  ensures ((reviewedEnd >= 0) ==> (reviewedEnd < (turns - 1)) ==> (candidateStart(turns, reviewedEnd, reviewedStart) == (reviewedEnd + 1)))
  ensures (((reviewedEnd == -1) || (reviewedEnd == (turns - 1))) ==> (reviewedStart >= 0) ==> (candidateStart(turns, reviewedEnd, reviewedStart) == reviewedStart))
  ensures (((reviewedEnd == -1) || (reviewedEnd == (turns - 1))) ==> (reviewedStart == -1) ==> (candidateStart(turns, reviewedEnd, reviewedStart) == 0))
{
}
