// Generated by lsc from review-estimate.ts

function JSFloorDiv(a: int, b: int): int
  requires b != 0
{
  if b > 0 then
    if a >= 0 then a / b
    else -((-a - 1) / b) - 1
  else
    if a <= 0 then (-a) / (-b)
    else -((a - 1) / (-b)) - 1
}

function JSRem(a: int, b: int): int
  requires b != 0
{
  var r := (if a < 0 then -a else a) % (if b < 0 then -b else b);
  if a < 0 then -r else r
}

datatype ReviewStatus = completed | incomplete

datatype MiddlePositionsResult = MiddlePositionsResult(lower: int, upper: int)

function canEstimate(count: int, minimum: int): bool
{
  ((minimum > 0) && (count >= minimum))
}

lemma canEstimate_ensures(count: int, minimum: int)
  ensures (canEstimate(count, minimum) == ((minimum > 0) && (count >= minimum)))
{
}

function middlePositions(length: int): MiddlePositionsResult
  requires (length > 0)
{
  var upper := JSFloorDiv(length, 2);
  MiddlePositionsResult((if (JSRem(length, 2) == 1) then upper else (upper - 1)), upper)
}

lemma middlePositions_ensures(length: int)
  requires (length > 0)
  ensures (0 <= middlePositions(length).lower)
  ensures (middlePositions(length).lower <= middlePositions(length).upper)
  ensures (middlePositions(length).upper < length)
  ensures (((middlePositions(length).lower + 1) * 2) >= length)
  ensures (((length - middlePositions(length).upper) * 2) >= length)
  ensures ((JSRem(length, 2) == 1) ==> (middlePositions(length).lower == middlePositions(length).upper))
  ensures ((JSRem(length, 2) == 0) ==> (middlePositions(length).upper == (middlePositions(length).lower + 1)))
{
}

function countsAsMeasurement(statuses: seq<ReviewStatus>): bool
{
  Std.Collections.Seq.All(statuses, (status: ReviewStatus) => status.completed?)
}

lemma countsAsMeasurement_ensures(statuses: seq<ReviewStatus>)
  ensures (countsAsMeasurement(statuses) == forall i: nat :: ((i < |statuses|) ==> statuses[i].completed?))
{
}
