// Generated by lsc from route-removal-rule.ts

datatype RouteAction = login | logout | remove

datatype RouteOutcome = keep | delete | refuse

function routeAfter(action: RouteAction, inUse: bool): RouteOutcome
{
  if (!action.remove?) then
    RouteOutcome.keep
  else
    if inUse then
      RouteOutcome.refuse
    else
      RouteOutcome.delete
}

lemma routeAfter_ensures(action: RouteAction, inUse: bool)
  ensures (routeAfter(action, inUse).keep? <==> (!action.remove?))
  ensures (routeAfter(action, inUse).refuse? <==> (action.remove? && inUse))
  ensures (routeAfter(action, inUse).delete? <==> (action.remove? && !(inUse)))
{
}
