// Generated by lsc from run-policy-rule.ts

datatype RunCommandAnswer = once | rule | deny

datatype RunNetworkAnswer = deny | session | repository

datatype RunStatus = not_started | completed | failed | cancelled | unsettled

function runCommandAnswer(allowed: bool): RunCommandAnswer
{
  if allowed then
    RunCommandAnswer.once
  else
    RunCommandAnswer.deny
}

lemma runCommandAnswer_ensures(allowed: bool)
  ensures (!runCommandAnswer(allowed).rule?)
  ensures (runCommandAnswer(allowed).once? == allowed)
{
}

function runNetworkAnswer(allowed: bool): RunNetworkAnswer
{
  if allowed then
    RunNetworkAnswer.session
  else
    RunNetworkAnswer.deny
}

lemma runNetworkAnswer_ensures(allowed: bool)
  ensures (!runNetworkAnswer(allowed).repository?)
  ensures (runNetworkAnswer(allowed).session? == allowed)
{
}

function runExitCode(status: RunStatus, blocked: bool, loop: int): int
{
  if (blocked || (loop != 0)) then
    1
  else
    if status.completed? then
      0
    else
      if status.cancelled? then
        130
      else
        1
}

lemma runExitCode_ensures(status: RunStatus, blocked: bool, loop: int)
  ensures ((runExitCode(status, blocked, loop) == 0) == ((status.completed? && !(blocked)) && (loop == 0)))
  ensures ((runExitCode(status, blocked, loop) == 130) == ((status.cancelled? && !(blocked)) && (loop == 0)))
  ensures (((runExitCode(status, blocked, loop) == 0) || (runExitCode(status, blocked, loop) == 1)) || (runExitCode(status, blocked, loop) == 130))
{
}
