// Generated by lsc from sandbox-qualification.ts

datatype FilesystemClaim = host | workspace

datatype NetworkClaim = open | allowlist

function qualifiedFilesystem(claimed: FilesystemClaim, processPassed: bool, filesystemPassed: bool): FilesystemClaim
{
  if (!claimed.workspace?) then
    FilesystemClaim.host
  else
    if (processPassed && filesystemPassed) then
      FilesystemClaim.workspace
    else
      FilesystemClaim.host
}

lemma qualifiedFilesystem_ensures(claimed: FilesystemClaim, processPassed: bool, filesystemPassed: bool)
  ensures (qualifiedFilesystem(claimed, processPassed, filesystemPassed).workspace? <==> ((claimed.workspace? && processPassed) && filesystemPassed))
{
}

function qualifiedNetwork(claimed: NetworkClaim, processPassed: bool, networkPassed: bool): NetworkClaim
{
  if (!claimed.allowlist?) then
    NetworkClaim.open
  else
    if (processPassed && networkPassed) then
      NetworkClaim.allowlist
    else
      NetworkClaim.open
}

lemma qualifiedNetwork_ensures(claimed: NetworkClaim, processPassed: bool, networkPassed: bool)
  ensures (qualifiedNetwork(claimed, processPassed, networkPassed).allowlist? <==> ((claimed.allowlist? && processPassed) && networkPassed))
{
}

function runsWithoutAsking(ready: bool, filesystem: FilesystemClaim, network: NetworkClaim): bool
{
  ((ready && filesystem.workspace?) && network.allowlist?)
}

lemma runsWithoutAsking_ensures(ready: bool, filesystem: FilesystemClaim, network: NetworkClaim)
  ensures (runsWithoutAsking(ready, filesystem, network) <==> ((ready && filesystem.workspace?) && network.allowlist?))
{
}
