// Generated by lsc from search-provider-rule.ts

datatype SearchStep = use | skip | fail

function searchStep(pinned: bool, isPinned: bool, available: bool): SearchStep
{
  if (pinned && !(isPinned)) then
    SearchStep.skip
  else
    if available then
      SearchStep.use
    else
      if pinned then
        SearchStep.fail
      else
        SearchStep.skip
}

lemma searchStep_ensures(pinned: bool, isPinned: bool, available: bool)
  ensures (pinned ==> !(isPinned) ==> searchStep(pinned, isPinned, available).skip?)
  ensures (pinned ==> isPinned ==> (searchStep(pinned, isPinned, available).use? <==> available))
  ensures (pinned ==> isPinned ==> (searchStep(pinned, isPinned, available).fail? <==> !(available)))
  ensures (!(pinned) ==> (searchStep(pinned, isPinned, available).use? <==> available))
  ensures (!(pinned) ==> (searchStep(pinned, isPinned, available).skip? <==> !(available)))
{
}

function searchContinues(pinned: bool): bool
{
  !(pinned)
}

lemma searchContinues_ensures(pinned: bool)
  ensures (searchContinues(pinned) <==> !(pinned))
{
}
