// Generated by lsc from search-provider-rule.ts

datatype SearchStep = use | skip | fail | ask

datatype SearchConsent = allowed | denied | unasked

function searchStep(pinned: bool, isPinned: bool, available: bool, keyless: bool, consent: SearchConsent): SearchStep
{
  if (pinned && !(isPinned)) then
    SearchStep.skip
  else
    if !(available) then
      if pinned then
        SearchStep.fail
      else
        SearchStep.skip
    else
      if ((pinned || !(keyless)) || consent.allowed?) then
        SearchStep.use
      else
        if consent.unasked? then
          SearchStep.ask
        else
          SearchStep.skip
}

lemma searchStep_ensures(pinned: bool, isPinned: bool, available: bool, keyless: bool, consent: SearchConsent)
  ensures (pinned ==> !(isPinned) ==> searchStep(pinned, isPinned, available, keyless, consent).skip?)
  ensures (searchStep(pinned, isPinned, available, keyless, consent).use? ==> (available && (!(pinned) || isPinned)))
  ensures (searchStep(pinned, isPinned, available, keyless, consent).use? ==> keyless ==> (isPinned || consent.allowed?))
  ensures (searchStep(pinned, isPinned, available, keyless, consent).ask? ==> (((keyless && !(pinned)) && available) && consent.unasked?))
  ensures (searchStep(pinned, isPinned, available, keyless, consent).fail? ==> ((pinned && isPinned) && !(available)))
  ensures (pinned ==> isPinned ==> (searchStep(pinned, isPinned, available, keyless, consent).use? <==> available))
  ensures (!(pinned) ==> !(keyless) ==> (searchStep(pinned, isPinned, available, keyless, consent).use? <==> available))
  ensures (!(pinned) ==> keyless ==> available ==> consent.allowed? ==> searchStep(pinned, isPinned, available, keyless, consent).use?)
  ensures (!(pinned) ==> keyless ==> consent.denied? ==> searchStep(pinned, isPinned, available, keyless, consent).skip?)
{
}

function searchContinues(pinned: bool): bool
{
  !(pinned)
}

lemma searchContinues_ensures(pinned: bool)
  ensures (searchContinues(pinned) <==> !(pinned))
{
}
