// Generated by lsc from secret-file-rule.ts

function hidesFile(secretName: bool, repository: bool, tracked: bool, allowed: bool): bool
{
  if (!(secretName) || allowed) then
    false
  else
    (!(repository) || !(tracked))
}

lemma hidesFile_ensures(secretName: bool, repository: bool, tracked: bool, allowed: bool)
  ensures (hidesFile(secretName, repository, tracked, allowed) <==> ((secretName && !(allowed)) && (!(repository) || !(tracked))))
  ensures (!(secretName) ==> !(hidesFile(secretName, repository, tracked, allowed)))
  ensures (secretName ==> !(allowed) ==> !(repository) ==> hidesFile(secretName, repository, tracked, allowed))
{
}
