// Generated by lsc from sensitive-path-rule.ts

function sensitivePath(declared: bool, isTest: bool, unambiguousTerm: bool, wholeAmbiguousTerm: bool, infrastructureFile: bool): bool
{
  (declared || (if isTest then false else ((unambiguousTerm || wholeAmbiguousTerm) || infrastructureFile)))
}

lemma sensitivePath_ensures(declared: bool, isTest: bool, unambiguousTerm: bool, wholeAmbiguousTerm: bool, infrastructureFile: bool)
  ensures (sensitivePath(declared, isTest, unambiguousTerm, wholeAmbiguousTerm, infrastructureFile) <==> (declared || (!(isTest) && ((unambiguousTerm || wholeAmbiguousTerm) || infrastructureFile))))
{
}
