// Generated by lsc from sensitive-path-rule.ts

function sensitivePath(declared: bool, confirmed: bool, isTest: bool, unambiguousTerm: bool, wholeAmbiguousTerm: bool, infrastructureFile: bool, importsAuthority: bool): bool
{
  (declared || (if isTest then false else (((unambiguousTerm || wholeAmbiguousTerm) || infrastructureFile) || (!(confirmed) && importsAuthority))))
}

lemma sensitivePath_ensures(declared: bool, confirmed: bool, isTest: bool, unambiguousTerm: bool, wholeAmbiguousTerm: bool, infrastructureFile: bool, importsAuthority: bool)
  ensures (sensitivePath(declared, confirmed, isTest, unambiguousTerm, wholeAmbiguousTerm, infrastructureFile, importsAuthority) <==> (declared || (!(isTest) && (((unambiguousTerm || wholeAmbiguousTerm) || infrastructureFile) || (!(confirmed) && importsAuthority)))))
{
}
