// Generated by lsc from session-title-rule.ts

datatype TitleSource = counter | request | generated | operator

function replacesTitle(current: TitleSource, next: TitleSource): bool
{
  (next.operator? || (if current.counter? then (!next.counter?) else (current.request? && next.generated?)))
}

lemma replacesTitle_ensures(current: TitleSource, next: TitleSource)
  ensures (replacesTitle(current, next) <==> ((next.operator? || (current.counter? && (!next.counter?))) || (current.request? && next.generated?)))
{
}
