// Generated by lsc from setup-network-rule.ts

datatype NetworkPhase = setup | agent

function permitted(allowed: bool, openedForSetup: bool, phase: NetworkPhase): bool
{
  (allowed || (phase.setup? && openedForSetup))
}

lemma permitted_ensures(allowed: bool, openedForSetup: bool, phase: NetworkPhase)
  ensures (permitted(allowed, openedForSetup, phase) <==> (allowed || (phase.setup? && openedForSetup)))
{
}
