// Generated by lsc from shell-theme-rule.ts

datatype ShellThemeName = tesota_dark | tesota_light | vesper | sequel | automata | phosphor | terminal

function acceptsShellTheme(value: string): bool
{
  (((((((value == "tesota-dark") || (value == "tesota-light")) || (value == "vesper")) || (value == "sequel")) || (value == "automata")) || (value == "phosphor")) || (value == "terminal"))
}

lemma acceptsShellTheme_ensures(value: string)
  ensures (acceptsShellTheme(value) <==> (((((((value == "tesota-dark") || (value == "tesota-light")) || (value == "vesper")) || (value == "sequel")) || (value == "automata")) || (value == "phosphor")) || (value == "terminal")))
{
}

const TESOTA_SHELL_THEME_NAMES: seq<string> := ["tesota-dark", "tesota-light", "vesper", "sequel", "automata", "phosphor", "terminal"]
