// Generated by lsc from sidebar-rule.ts

datatype SidebarPreference = auto | open | hidden

datatype SidebarPresentation = hidden | inline | overlay

datatype SidebarProgressPhase = none | preparing | working | awaiting_command | checking | reviewing | awaiting_decision | applying

datatype SidebarSessionState = preparing | working | awaiting_command | checking | reviewing | awaiting_decision | applying | unresolved | ended | needs_operator | unread | idle

function sidebarPresentation(preference: SidebarPreference, width: int): SidebarPresentation
{
  if preference.hidden? then
    SidebarPresentation.hidden
  else
    if (width >= SIDEBAR_INLINE_MIN_WIDTH) then
      SidebarPresentation.inline
    else
      if preference.open? then
        SidebarPresentation.overlay
      else
        SidebarPresentation.hidden
}

lemma sidebarPresentation_ensures(preference: SidebarPreference, width: int)
  ensures (preference.hidden? ==> sidebarPresentation(preference, width).hidden?)
  ensures ((!preference.hidden?) ==> (width >= 88) ==> sidebarPresentation(preference, width).inline?)
  ensures (preference.open? ==> (width < 88) ==> sidebarPresentation(preference, width).overlay?)
  ensures (preference.auto? ==> (width < 88) ==> sidebarPresentation(preference, width).hidden?)
{
}

function sidebarSessionState(blocked: bool, ended: bool, needsOperator: bool, phase: SidebarProgressPhase, unread: bool): SidebarSessionState
{
  if blocked then
    SidebarSessionState.unresolved
  else
    if ended then
      SidebarSessionState.ended
    else
      if phase.awaiting_command? then
        SidebarSessionState.awaiting_command
      else
        if phase.awaiting_decision? then
          SidebarSessionState.awaiting_decision
        else
          if needsOperator then
            SidebarSessionState.needs_operator
          else
            if phase.preparing? then
              SidebarSessionState.preparing
            else
              if phase.working? then
                SidebarSessionState.working
              else
                if phase.checking? then
                  SidebarSessionState.checking
                else
                  if phase.reviewing? then
                    SidebarSessionState.reviewing
                  else
                    if phase.applying? then
                      SidebarSessionState.applying
                    else
                      if unread then
                        SidebarSessionState.unread
                      else
                        SidebarSessionState.idle
}

lemma sidebarSessionState_ensures(blocked: bool, ended: bool, needsOperator: bool, phase: SidebarProgressPhase, unread: bool)
  ensures (blocked ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).unresolved?)
  ensures (!(blocked) ==> ended ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).ended?)
  ensures (!(blocked) ==> !(ended) ==> phase.awaiting_command? ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).awaiting_command?)
  ensures (!(blocked) ==> !(ended) ==> phase.awaiting_decision? ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).awaiting_decision?)
  ensures (!(blocked) ==> !(ended) ==> (!phase.awaiting_command?) ==> (!phase.awaiting_decision?) ==> needsOperator ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).needs_operator?)
  ensures (!(blocked) ==> !(ended) ==> !(needsOperator) ==> phase.preparing? ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).preparing?)
  ensures (!(blocked) ==> !(ended) ==> !(needsOperator) ==> phase.working? ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).working?)
  ensures (!(blocked) ==> !(ended) ==> !(needsOperator) ==> phase.checking? ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).checking?)
  ensures (!(blocked) ==> !(ended) ==> !(needsOperator) ==> phase.reviewing? ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).reviewing?)
  ensures (!(blocked) ==> !(ended) ==> !(needsOperator) ==> phase.applying? ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).applying?)
  ensures (!(blocked) ==> !(ended) ==> !(needsOperator) ==> phase.none? ==> unread ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).unread?)
  ensures (!(blocked) ==> !(ended) ==> !(needsOperator) ==> phase.none? ==> !(unread) ==> sidebarSessionState(blocked, ended, needsOperator, phase, unread).idle?)
{
}

function animatedSidebarState(state: SidebarSessionState): bool
{
  ((((state.preparing? || state.working?) || state.checking?) || state.reviewing?) || state.applying?)
}

lemma animatedSidebarState_ensures(state: SidebarSessionState)
  ensures (animatedSidebarState(state) == ((((state.preparing? || state.working?) || state.checking?) || state.reviewing?) || state.applying?))
{
}

function newestFirstSourceIndex(count: int, visual: int): int
{
  if (((count <= 0) || (visual < 0)) || (visual >= count)) then
    -1
  else
    ((count - visual) - 1)
}

lemma newestFirstSourceIndex_ensures(count: int, visual: int)
  ensures ((((count <= 0) || (visual < 0)) || (visual >= count)) ==> (newestFirstSourceIndex(count, visual) == -1))
  ensures ((count > 0) ==> (visual >= 0) ==> (visual < count) ==> (newestFirstSourceIndex(count, visual) == ((count - visual) - 1)))
{
}

const SIDEBAR_INLINE_MIN_WIDTH: int := 88
