// Generated by lsc from source-holder-rule.ts

function holdsSourceFiles(starting: bool, inSource: bool, running: bool, undecided: bool): bool
{
  (starting || (inSource && (running || undecided)))
}

lemma holdsSourceFiles_ensures(starting: bool, inSource: bool, running: bool, undecided: bool)
  ensures (starting ==> holdsSourceFiles(starting, inSource, running, undecided))
  ensures (inSource ==> running ==> holdsSourceFiles(starting, inSource, running, undecided))
  ensures (inSource ==> undecided ==> holdsSourceFiles(starting, inSource, running, undecided))
  ensures (!(starting) ==> !(inSource) ==> !(holdsSourceFiles(starting, inSource, running, undecided)))
  ensures (!(starting) ==> !(running) ==> !(undecided) ==> !(holdsSourceFiles(starting, inSource, running, undecided)))
{
}

function worksInSourceFiles(repository: bool, chosenCopy: bool, heldElsewhere: bool): bool
{
  ((repository && !(chosenCopy)) && !(heldElsewhere))
}

lemma worksInSourceFiles_ensures(repository: bool, chosenCopy: bool, heldElsewhere: bool)
  ensures (worksInSourceFiles(repository, chosenCopy, heldElsewhere) ==> repository)
  ensures (worksInSourceFiles(repository, chosenCopy, heldElsewhere) ==> !(chosenCopy))
  ensures (worksInSourceFiles(repository, chosenCopy, heldElsewhere) ==> !(heldElsewhere))
  ensures (repository ==> !(chosenCopy) ==> !(heldElsewhere) ==> worksInSourceFiles(repository, chosenCopy, heldElsewhere))
{
}
