// Generated by lsc from test-weakening-rule.ts

datatype ChangeStatus = added | modified | deleted

function removalCounts(blank: bool, comment: bool, widenedImport: bool): bool
{
  ((!(blank) && !(comment)) && !(widenedImport))
}

lemma removalCounts_ensures(blank: bool, comment: bool, widenedImport: bool)
  ensures (removalCounts(blank, comment, widenedImport) <==> ((!(blank) && !(comment)) && !(widenedImport)))
{
}

function testWeakens(status: ChangeStatus, removes: bool, changesRuns: bool): bool
{
  (status.deleted? || (status.modified? && (removes || changesRuns)))
}

lemma testWeakens_ensures(status: ChangeStatus, removes: bool, changesRuns: bool)
  ensures (testWeakens(status, removes, changesRuns) <==> (status.deleted? || (status.modified? && (removes || changesRuns))))
{
}
