// Generated by lsc from tool-folder-rule.ts

function readsToolFolder(holdsHome: bool, onWindowsDrive: bool, systemFolder: bool): bool
{
  if (holdsHome || onWindowsDrive) then
    false
  else
    !(systemFolder)
}

lemma readsToolFolder_ensures(holdsHome: bool, onWindowsDrive: bool, systemFolder: bool)
  ensures (readsToolFolder(holdsHome, onWindowsDrive, systemFolder) <==> ((!(holdsHome) && !(onWindowsDrive)) && !(systemFolder)))
{
}
