// Generated by lsc from toolchain-refresh-rule.ts

datatype ToolchainStep = unchanged_ | unavailable | ask

function toolchainStep(changed: bool, refreshable: bool): ToolchainStep
{
  if !(changed) then
    ToolchainStep.unchanged_
  else
    if refreshable then
      ToolchainStep.ask
    else
      ToolchainStep.unavailable
}

lemma toolchainStep_ensures(changed: bool, refreshable: bool)
  ensures (toolchainStep(changed, refreshable).unchanged_? <==> !(changed))
  ensures (toolchainStep(changed, refreshable).unavailable? <==> (changed && !(refreshable)))
  ensures (toolchainStep(changed, refreshable).ask? <==> (changed && refreshable))
{
}

function installsDeclaredTools(changed: bool, refreshable: bool, approved: bool): bool
{
  (toolchainStep(changed, refreshable).ask? && approved)
}

lemma installsDeclaredTools_ensures(changed: bool, refreshable: bool, approved: bool)
  ensures (installsDeclaredTools(changed, refreshable, approved) <==> ((changed && refreshable) && approved))
{
}
