// Generated by lsc from turn-time-limit.ts

datatype EngineTurnStatus = completed | failed | cancelled | unsettled

datatype LimitedTurnStatus = completed | failed | cancelled | unsettled | timed_out

function limitedTurnStatus(status: EngineTurnStatus, limitReached: bool, callerStopped: bool): LimitedTurnStatus
{
  if status.completed? then
    LimitedTurnStatus.completed
  else
    if status.failed? then
      LimitedTurnStatus.failed
    else
      if status.unsettled? then
        LimitedTurnStatus.unsettled
      else
        if (limitReached && !(callerStopped)) then
          LimitedTurnStatus.timed_out
        else
          LimitedTurnStatus.cancelled
}

lemma limitedTurnStatus_ensures(status: EngineTurnStatus, limitReached: bool, callerStopped: bool)
  ensures (status.completed? ==> limitedTurnStatus(status, limitReached, callerStopped).completed?)
  ensures (status.failed? ==> limitedTurnStatus(status, limitReached, callerStopped).failed?)
  ensures (status.unsettled? ==> limitedTurnStatus(status, limitReached, callerStopped).unsettled?)
  ensures (status.cancelled? ==> limitReached ==> !(callerStopped) ==> limitedTurnStatus(status, limitReached, callerStopped).timed_out?)
  ensures (status.cancelled? ==> (!(limitReached) || callerStopped) ==> limitedTurnStatus(status, limitReached, callerStopped).cancelled?)
{
}
