// Generated by lsc from usage-reader-rule.ts

method usageReader(accounts: seq<string>, route: int) returns (res: int)
  requires (0 <= route)
  requires (route < |accounts|)
  ensures (0 <= res)
  ensures (res <= route)
  ensures ((accounts[route] == "") ==> (res == route))
  ensures ((accounts[route] != "") ==> (accounts[res] == accounts[route]))
  ensures ((accounts[route] != "") ==> forall j: nat :: ((j < res) ==> (accounts[j] != accounts[route])))
{
  if (accounts[route] == "") {
    return route;
  }
  var i := 0;
  while (i < route)
    invariant (0 <= i)
    invariant (i <= route)
    invariant forall j: nat :: ((j < i) ==> (accounts[j] != accounts[route]))
  {
    if (accounts[i] == accounts[route]) {
      return i;
    }
    i := (i + 1);
  }
  return route;
}
