// Generated by lsc from usage-meter-rule.ts

function JSFloorDiv(a: int, b: int): int
  requires b != 0
{
  if b > 0 then
    if a >= 0 then a / b
    else -((-a - 1) / b) - 1
  else
    if a <= 0 then (-a) / (-b)
    else -((a - 1) / (-b)) - 1
}

datatype MeterTone = ok | low | out

function remainingPercent(used: int): int
{
  if (used <= 0) then
    100
  else
    if (used >= 100) then
      0
    else
      (100 - used)
}

lemma remainingPercent_ensures(used: int)
  ensures ((used <= 0) ==> (remainingPercent(used) == 100))
  ensures ((used >= 100) ==> (remainingPercent(used) == 0))
  ensures ((0 < used) ==> (used < 100) ==> (remainingPercent(used) == (100 - used)))
{
}

function creditPercent(remaining: int, limit: int): int
  requires (limit > 0)
{
  if (remaining >= limit) then
    100
  else
    if (remaining <= 0) then
      0
    else
      JSFloorDiv((remaining * 100), limit)
}

lemma creditPercent_ensures(remaining: int, limit: int)
  requires (limit > 0)
  ensures (0 <= creditPercent(remaining, limit))
  ensures (creditPercent(remaining, limit) <= 100)
  ensures ((remaining >= limit) ==> (creditPercent(remaining, limit) == 100))
  ensures ((remaining <= 0) ==> (creditPercent(remaining, limit) == 0))
  ensures ((0 < remaining) ==> (remaining < limit) ==> (((creditPercent(remaining, limit) * limit) <= (remaining * 100)) && ((remaining * 100) < ((creditPercent(remaining, limit) + 1) * limit))))
{
}

function filledSegments(percent: int, segments: int): int
  requires (segments >= 2)
{
  if (percent <= 0) then
    0
  else
    if (percent >= 100) then
      segments
    else
      var nearest := JSFloorDiv(((percent * segments) + 50), 100);
      if (nearest < 1) then
        1
      else
        if (nearest > (segments - 1)) then
          (segments - 1)
        else
          nearest
}

lemma filledSegments_ensures(percent: int, segments: int)
  requires (segments >= 2)
  ensures (0 <= filledSegments(percent, segments))
  ensures (filledSegments(percent, segments) <= segments)
  ensures ((filledSegments(percent, segments) == 0) <==> (percent <= 0))
  ensures ((filledSegments(percent, segments) == segments) <==> (percent >= 100))
{
}

function meterTone(left: int): MeterTone
{
  if (left <= 0) then
    MeterTone.out
  else
    if (left <= 25) then
      MeterTone.low
    else
      MeterTone.ok
}

lemma meterTone_ensures(left: int)
  ensures (meterTone(left).out? <==> (left <= 0))
  ensures (meterTone(left).low? <==> ((0 < left) && (left <= 25)))
  ensures (meterTone(left).ok? <==> (left > 25))
{
}
