// Generated by lsc from verdict-rule.ts

datatype Standing = decide | gap | holds | opinion

method decisions(standings: seq<Standing>) returns (res: int)
  ensures (0 <= res)
  ensures (res <= |standings|)
  ensures ((res == 0) <==> !(exists k: nat :: ((k < |standings|) && standings[k].decide?)))
{
  var count := 0;
  var k := 0;
  while (k < |standings|)
    invariant (0 <= k)
    invariant (k <= |standings|)
    invariant (0 <= count)
    invariant (count <= k)
    invariant ((count == 0) <==> !(exists j: nat :: ((j < k) && standings[j].decide?)))
  {
    if standings[k].decide? {
      count := (count + 1);
    }
    k := (k + 1);
  }
  return count;
}
