// Generated by lsc from weakening-rule.ts

datatype AnnotationKind = requires_ | ensures_ | assume_ | other

function weakens(kind: AnnotationKind, removed: bool, matched: bool): bool
{
  if matched then
    false
  else
    if removed then
      (kind.requires_? || kind.ensures_?)
    else
      kind.assume_?
}

lemma weakens_ensures(kind: AnnotationKind, removed: bool, matched: bool)
  ensures (weakens(kind, removed, matched) <==> (!(matched) && ((removed && (kind.requires_? || kind.ensures_?)) || (!(removed) && kind.assume_?))))
{
}
