// Generated by lsc from web-admission.ts

datatype WebPermission = allowed | denied | unasked

datatype WebAdmission = fetch | ask | deny | refuse_url | refuse_address

function webAdmission(validUrl: bool, permission: WebPermission, publicAddress: bool): WebAdmission
{
  if !(validUrl) then
    WebAdmission.refuse_url
  else
    if permission.denied? then
      WebAdmission.deny
    else
      if permission.unasked? then
        WebAdmission.ask
      else
        if !(publicAddress) then
          WebAdmission.refuse_address
        else
          WebAdmission.fetch
}

lemma webAdmission_ensures(validUrl: bool, permission: WebPermission, publicAddress: bool)
  ensures (!(validUrl) ==> webAdmission(validUrl, permission, publicAddress).refuse_url?)
  ensures (validUrl ==> permission.denied? ==> webAdmission(validUrl, permission, publicAddress).deny?)
  ensures (validUrl ==> permission.unasked? ==> webAdmission(validUrl, permission, publicAddress).ask?)
  ensures (validUrl ==> permission.allowed? ==> !(publicAddress) ==> webAdmission(validUrl, permission, publicAddress).refuse_address?)
  ensures (webAdmission(validUrl, permission, publicAddress).fetch? <==> ((validUrl && permission.allowed?) && publicAddress))
{
}
