// Generated by lsc from wsl-settings-rule.ts

datatype MountFilesystem = drvfs | plan9 | other

datatype DistributionStep = setup | restart | ready

function countsAsDrive(filesystem: MountFilesystem, drvfsShare: bool, driveRoot: bool): bool
{
  if !(driveRoot) then
    false
  else
    (filesystem.drvfs? || (filesystem.plan9? && drvfsShare))
}

lemma countsAsDrive_ensures(filesystem: MountFilesystem, drvfsShare: bool, driveRoot: bool)
  ensures (countsAsDrive(filesystem, drvfsShare, driveRoot) <==> (driveRoot && (filesystem.drvfs? || (filesystem.plan9? && drvfsShare))))
{
}

function settingsAsked(interopOff: bool, uidMatches: bool, gidMatches: bool): bool
{
  ((interopOff && uidMatches) && gidMatches)
}

lemma settingsAsked_ensures(interopOff: bool, uidMatches: bool, gidMatches: bool)
  ensures (settingsAsked(interopOff, uidMatches, gidMatches) <==> ((interopOff && uidMatches) && gidMatches))
{
}

function distributionStep(setupMissing: bool, settingsPending: bool): DistributionStep
{
  if setupMissing then
    DistributionStep.setup
  else
    if settingsPending then
      DistributionStep.restart
    else
      DistributionStep.ready
}

lemma distributionStep_ensures(setupMissing: bool, settingsPending: bool)
  ensures (distributionStep(setupMissing, settingsPending).setup? <==> setupMissing)
  ensures (distributionStep(setupMissing, settingsPending).restart? <==> (!(setupMissing) && settingsPending))
{
}
